// Code generated by MockGen. DO NOT EDIT.
// Source: enriched_event_repository.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/openshift-assisted/assisted-events-streams/internal/types"
)

// MockEnrichedEventRepositoryInterface is a mock of EnrichedEventRepositoryInterface interface.
type MockEnrichedEventRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEnrichedEventRepositoryInterfaceMockRecorder
}

// MockEnrichedEventRepositoryInterfaceMockRecorder is the mock recorder for MockEnrichedEventRepositoryInterface.
type MockEnrichedEventRepositoryInterfaceMockRecorder struct {
	mock *MockEnrichedEventRepositoryInterface
}

// NewMockEnrichedEventRepositoryInterface creates a new mock instance.
func NewMockEnrichedEventRepositoryInterface(ctrl *gomock.Controller) *MockEnrichedEventRepositoryInterface {
	mock := &MockEnrichedEventRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockEnrichedEventRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrichedEventRepositoryInterface) EXPECT() *MockEnrichedEventRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockEnrichedEventRepositoryInterface) Store(ctx context.Context, enrichedEvent *types.EnrichedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, enrichedEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockEnrichedEventRepositoryInterfaceMockRecorder) Store(ctx, enrichedEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockEnrichedEventRepositoryInterface)(nil).Store), ctx, enrichedEvent)
}
